// Hand-written level names (20 per world).
export const NAMES = [
  ['Hello, Pan', 'Shelf Starter', 'Mug Shot', 'Toast of the Town', 'Pop Goes the Wiener', 'Counter Intelligence', 'Book Smart', 'Butter Luck Next Time', 'Slippery Slope', 'Knife to Meet You', 'Pot Luck', 'Hot Stuff', 'Burner Notice', 'Fridge Benefits', 'Cereal Offender', 'Microwave Goodbye', 'Blender Bender', 'Spice Spice Baby', 'Kitchen Nightmare', 'Chef\'s Kiss'],
  ['Couch Potato', 'Sofa So Good', 'Cushion Push-in', 'Remote Control', 'Cat Nap', 'Let Sleeping Cats Lie', 'Lamp Shady', 'Clockwork Frank', 'Time Flies', 'Fish Out of Water', 'Piano Man', 'Bean There', 'Armchair Expert', 'Global Warming', 'Fire Starter', 'Mantel Piece', 'Shelf Help', 'Living on the Edge', 'Prime Time', 'Grand Finale'],
  ['Grill Seeker', 'Bounce House', 'Tramp-o-lean', 'Swing State', 'Fence Sitter', 'Gnome Sweet Gnome', 'Leaf Me Alone', 'Blown Away', 'Sprinkle Sprinkle', 'Bird Bath Bomb', 'Who Let the Dog Out', 'Lawn and Order', 'Stump Speech', 'Cool Runnings', 'Flare-Up', 'Branching Out', 'Picnic Panic', 'Barbecue Bonanza', 'Sausage Party', 'Backyard Boss'],
  ['Rub-a-Dub Dog', 'Soap Opera', 'Slip \'n\' Slide', 'Duck Duck Bounce', 'Squeaky Clean', 'Shower Power', 'Towel Trouble', 'Scale of One to Ten', 'Hair Raiser', 'Flush Hour', 'Bath Bombs Away', 'Tub Thumping', 'Mirror Mirror', 'Toilet Humor', 'Sink or Swim', 'Bubble Trouble', 'Steamed', 'Loo-sing Streak', 'Royal Flush', 'Spa Day'],
  ['Desk Job', 'Paper Pusher', 'Staple Diet', 'Rolling Chair', 'Fan Mail', 'Shred Alert', 'Cubicle Hop', 'Coffee Break', 'Water Cooler Talk', 'Print Screen', 'Filing Frenzy', 'Monitor Lizard', 'Vending Venture', 'Overtime', 'Casual Friday', 'Team Building', 'Reply All', 'Synergy', 'Promotion', 'Corner Office'],
  ['Block Party', 'Easy as ABC', 'Drum Roll', 'Choo Choo Chew', 'Teddy or Not', 'Jack in the Bun', 'Pop Goes the Weasel', 'Xylo-phonic', 'Pinwheel of Fortune', 'Toy Story', 'Rocking Horse Winner', 'Balloon Ride', 'Up, Up and Away', 'Playtime', 'Bedtime Story', 'Building Blocks', 'Merry-Go-Round', 'Toy Box Tycoon', 'Lights Out', 'Nap Time Showdown'],
  ['Clean Up Aisle Five', 'Cart Wheel', 'Belt It Out', 'Price Check', 'Can Do', 'Crate Expectations', 'Frozen Assets', 'Cold Shoulder', 'Deli Belly', 'Lobster Tanked', 'Bulk Buy', 'Express Lane', 'Coupon Clipper', 'Shelf Stocker', 'Bag It', 'Two for One', 'Free Samples', 'Fresh Produce', 'Checkout Champion', 'Customer Service'],
  ['Shore Thing', 'Sandy Bottoms', 'Ball\'s in Your Court', 'Crabby Patty', 'Surf\'s Up', 'Lifeguard on Duty', 'Gull-ible', 'Pail Ale', 'Palm Reader', 'Buoy Oh Buoy', 'Beach Bum', 'Tide Turner', 'Sun Burnt', 'Shell Shocked', 'Castle Crasher', 'Wave Goodbye', 'Boardwalk Empire', 'Seas the Day', 'Sea Dog', 'Sunset Sizzle'],
  ['One Small Flip', 'Zero-G Frank', 'Houston, a Hot Dog', 'Satellite of Love', 'Rocky Asteroid', 'Pew Pew', 'Beam Me Up', 'Gravity Falls', 'Space Bun', 'Moon Walker', 'UFO Sighting', 'Orbit Frank', 'Rocket Man', 'Star Dog', 'Cosmic Relish', 'Milky Wiener', 'Black Hole Bun', 'Lost in Space', 'Mission Control', 'Interstellar'],
  ['Cloud Nine', 'Ketchup Kingdom', 'Mustard Mountain', 'Burger Bounce', 'Fry Me to the Moon', 'Soda Pop', 'Donut Disturb', 'Cotton Candy Crush', 'In a Pickle', 'Fork in the Road', 'Deep Fried Dreams', 'Relish the Moment', 'Condiment Canyon', 'Bun in a Million', 'Pearly Grill', 'Heavenly Hot Dog', 'Sauce of All Evil', 'Golden Gates', 'The Final Flip', 'Top Dog'],
];
