// Hand-written level names (20 per world).
export const NAMES = [
  ['Hello, Pan', 'Shelf Starter', 'Book Smart', 'Toast of the Town', 'Pop Goes the Wiener', 'Counter Intelligence', 'Fridge Benefits', 'Mug Shot', 'Slippery Slope', 'Knife to Meet You', 'Butter Luck Next Time', 'Pot Luck', 'Burner Notice', 'Chopping Block', 'Cereal Offender', 'Novel Approach', 'Microwave Goodbye', 'Spice Spice Baby', 'Kitchen Nightmare', 'Chef\'s Kiss'],
  ['Couch Potato', 'Armchair Expert', 'Remote Control', 'Plant Based', 'Cat Nap', 'Shelf Help', 'Pillow Talk', 'Clockwork Frank', 'Lamp Shady', 'Reading Nook', 'Cushion Push-in', 'Bean There', 'Bean Bag Bonanza', 'Channel Surfing', 'Fire Starter', 'Page Turner', 'Piano Man', 'Living on the Edge', 'Prime Time', 'Grand Finale'],
  ['Branching Out', 'Bounce House', 'Lounge Act', 'Swing State', 'Picnic Panic', 'Tramp-o-lean', 'Leaf Me Alone', 'Cool Runnings', 'Sprinkle Sprinkle', 'Blown Away', 'Who Let the Dog Out', 'Lawn and Order', 'Stump Speech', 'Splash Zone', 'Flare-Up', 'Grill Seeker', 'Stumped', 'Barbecue Bonanza', 'Sausage Party', 'Backyard Boss'],
  ['Rub-a-Dub Dog', 'Royal Flush', 'Sink or Swim', 'Duck Duck Bounce', 'Squeaky Clean', 'Shower Power', 'Scale of One to Ten', 'Soap Opera', 'Hair Raiser', 'Flush Hour', 'Towel Trouble', 'Tub Thumping', 'Suds Up', 'Toilet Humor', 'Hot Air', 'Bubble Trouble', 'Mirror Mirror', 'Loo-sing Streak', 'Scale Model', 'Spa Day'],
  ['Filing Frenzy', 'Print Screen', 'Water Cooler Talk', 'Rolling Chair', 'Fan Mail', 'Paper Pusher', 'Shred Alert', 'Coffee Break', 'Snack Attack', 'In the Loop', 'Staple Diet', 'Toner Low', 'Vending Venture', 'Overtime', 'Casual Friday', 'Team Building', 'Reply All', 'Synergy', 'Promotion', 'Corner Office'],
  ['Horsing Around', 'Easy as ABC', 'Drum Roll', 'Pop Goes the Weasel', 'Surprise Inside', 'Jack in the Bun', 'Block Party', 'Xylo-phonic', 'Choo Choo Chew', 'Toy Story', 'Rocking Horse Winner', 'Toy Piano', 'Up, Up and Away', 'Playtime', 'Bedtime Story', 'Building Blocks', 'Merry-Go-Round', 'Toy Box Tycoon', 'Teddy or Not', 'Nap Time Showdown'],
  ['Clean Up Aisle Five', 'Can Do', 'Belt It Out', 'Price Check', 'Cart Wheel', 'Crate Expectations', 'Frozen Assets', 'Cold Shoulder', 'Deli Belly', 'Bulk Buy', 'Lobster Tanked', 'Express Lane', 'Coupon Clipper', 'Shelf Stocker', 'Bag It', 'Two for One', 'Free Samples', 'Fresh Produce', 'Checkout Champion', 'Customer Service'],
  ['Shore Thing', 'Sandy Bottoms', 'Ball\'s in Your Court', 'Crabby Patty', 'Castle Crasher', 'Shady Spot', 'Crab Walk', 'Lifeguard on Duty', 'Gull-ible', 'Buoy Oh Buoy', 'Surf\'s Up', 'Pail Ale', 'Sun Burnt', 'Shell Shocked', 'Cooler Heads', 'Wave Goodbye', 'Boardwalk Empire', 'Seas the Day', 'Sea Dog', 'Sunset Sizzle'],
  ['One Small Flip', 'Zero-G Frank', 'Houston, a Hot Dog', 'Hover Craft', 'Satellite of Love', 'Rocky Asteroid', 'Beam Me Up', 'Gravity Falls', 'Space Bun', 'Moon Walker', 'UFO Sighting', 'Orbit Frank', 'Rocket Man', 'Star Dog', 'Cosmic Relish', 'Milky Wiener', 'Black Hole Bun', 'Lost in Space', 'Mission Control', 'Interstellar'],
  ['Cloud Nine', 'Small Fry', 'Donut Disturb', 'Burger Bounce', 'Fry Me to the Moon', 'Fork in the Road', 'Double Patty', 'French Connection', 'Fryer Tuck', 'Fry Day', 'Deep Fried Dreams', 'Cotton Candy Crush', 'In a Pickle', 'Bun in a Million', 'Pearly Grill', 'Heavenly Hot Dog', 'Sauce of All Evil', 'Golden Gates', 'The Final Flip', 'Top Dog'],
];
