// Regenerate a single level in place (keeps every other level untouched), optionally with an easier target.
// node tools/regen-one.mjs <levelNumber> [targetPar] [minRobust] [--out file.json]    then: node tools/tune-par.mjs
import fs from 'node:fs';
import path from 'node:path';
import { generateOne } from './generate.mjs';
import { replaySolution } from './solver.mjs';
const argv = process.argv.slice(2);
const outIdx = argv.indexOf('--out');
const out = outIdx >= 0 ? argv.splice(outIdx, 2)[1] : null; // write to a JSON file instead (for parallel runs; merge with tools/resolve.mjs --apply)
const n = +argv[0], i = n - 1;
const target = {};
if (argv[1]) target.par = +argv[1];
if (argv[2]) target.robust = +argv[2];
const file = path.resolve('src/levels/data.js');
const { LEVELS } = await import(file + '?t=' + Date.now());
const old = LEVELS[i];
const lvl = generateOne(i, { target, maxAttempts: 30 });
const { meta, targetPar, ...clean } = lvl;
if (replaySolution(clean, Math.floor(i / 20)) !== 'win') throw new Error('new level does not replay');
if (old.tip && !clean.tip) clean.tip = old.tip;
if (out) { fs.writeFileSync(out, JSON.stringify({ [n]: { level: clean } })); console.log(`#${n} → ${out}: min ${clean.par}, robust ${meta && meta.robust}`); process.exit(0); }
LEVELS[i] = clean; // par = solver minimum; tune-par adds slack and sets minFlips
fs.writeFileSync(file, '// AUTO-GENERATED by tools/generate.mjs (+ tools/tune-par.mjs) — every level verified solvable by tools/solver.mjs\nexport const LEVELS = ' + JSON.stringify(LEVELS) + ';\n');
console.log(`#${n} ${clean.name}: par ${old.par}/min ${old.minFlips} → min ${clean.par}, robust ${meta && meta.robust}, objs ${clean.objects.length}, tip: ${(clean.tip || '').replace(/<[^>]+>/g, '')}`);
