// Re-solve the route of existing levels (layout unchanged) and write it back to src/levels/data.js.
// Use after a physics change that invalidates stored routes. Then run: node tools/tune-par.mjs
// node tools/resolve.mjs --solve 59,83 --out /tmp/x.json     (search; writes results)
// node tools/resolve.mjs --apply /tmp/x.json [/tmp/y.json…]   (merge results into data.js)
import fs from 'node:fs';
import path from 'node:path';
import { solve, replaySolution } from './solver.mjs';
const args = process.argv.slice(2);
const file = path.resolve('src/levels/data.js');
const { LEVELS } = await import(file + '?t=' + Date.now());
if (args[0] === '--solve') {
  const ids = args[1].split(',').map(Number), out = args[3];
  const res = {};
  for (const n of ids) {
    const i = n - 1, L = LEVELS[i], w = Math.floor(i / 20);
    const t0 = Date.now();
    const min = L.minFlips ?? L.par;
    let sol = solve(L, w, { maxDepth: min + 2, beam: 6 });
    if (!sol.par) sol = solve(L, w, { maxDepth: min + 3, beam: 8, minEdge: 0.06 });
    const solution = sol.par ? sol.path.map(s => [s.a, s.p, s.delay || 0]) : null;
    const ok = solution && replaySolution(L, w, solution) === 'win';
    res[n] = ok ? { solution, par: sol.par, robust: sol.minRobust } : null;
    console.log(`L${n}: ${ok ? `min ${min} → ${sol.par}, robust ${(+sol.minRobust).toFixed(2)}` : 'NO ROUTE'} (${((Date.now() - t0) / 1000).toFixed(0)}s)`);
    fs.writeFileSync(out, JSON.stringify(res));
  }
} else if (args[0] === '--apply') {
  for (const f of args.slice(1)) {
    const res = JSON.parse(fs.readFileSync(f, 'utf8'));
    for (const [n, r] of Object.entries(res)) {
      if (!r) { console.log(`L${n}: no route — left unchanged`); continue; }
      if (r.level) { LEVELS[n - 1] = r.level; console.log(`L${n}: new layout, ${r.level.par} flips`); continue; }
      const L = LEVELS[n - 1];
      L.solution = r.solution; L.par = r.par; delete L.minFlips; // tune-par recomputes slack + minFlips
      console.log(`L${n}: new route, ${r.par} flips`);
    }
  }
  fs.writeFileSync(file, '// AUTO-GENERATED by tools/generate.mjs (+ tools/tune-par.mjs) — every level verified solvable by tools/solver.mjs\nexport const LEVELS = ' + JSON.stringify(LEVELS) + ';\n');
}
