// After a change to when the sausage counts as "ready to flip" (Sim.canLaunch), the stored routes' waits — counted
// from the moment it becomes ready — no longer line up. This keeps every route's flips at exactly the same
// physics step as before: it replays each route with the previous physics, notes the step of every flip, and
// rewrites the waits so the current physics flips at those same steps. Then it checks every route still wins.
// node tools/retime-routes.mjs --old <path/to/previous/src/physics.js> [--write]
import fs from 'node:fs';
import path from 'node:path';
import { PHYS, Sim } from '../src/physics.js';
import { WORLDS } from '../src/objects.js';
import { LEVELS } from '../src/levels/data.js';

const args = process.argv.slice(2);
const oldPath = args.includes('--old') ? path.resolve(args[args.indexOf('--old') + 1]) : null;
if (!oldPath) { console.error('usage: node tools/retime-routes.mjs --old <previous physics.js> [--write]'); process.exit(1); }
const Old = await import(oldPath);

function start(SimC, L, wi) {
  const w = WORLDS[wi];
  const sim = new SimC({ ...L, gravity: L.gravity ?? w.gravity, floor: L.floor ?? w.floor }, { events: false });
  sim.placeSausage(L.start[0], L.start[1], L.start[2] || 0);
  for (let i = 0; i < 90; i++) sim.step();
  sim.t = 0;
  for (const b of sim.bodies) sim.updateBody(b, 0, true);
  let n = 0;
  for (let i = 0; i < 120 && !sim.canLaunch(); i++) { sim.step(); n++; }
  return { sim, steps: n };
}

// replay a route; returns the step of every flip and the outcome
function replay(SimC, L, wi, waits) {
  const { sim, steps: s0 } = start(SimC, L, wi);
  let steps = s0;
  const at = [];
  L.solution.forEach(([a, p], k) => {
    if (sim.status !== 'play') return;
    const w = waits[k];
    for (let i = 0; i < w && sim.status === 'play'; i++) { sim.step(); steps++; }
    if (sim.status !== 'play') return;
    at.push({ step: steps, x: sim.px[4], y: sim.py[4], ready: sim.canLaunch() });
    const [vx, vy] = SimC.clampLaunch(Math.cos(a), Math.sin(a), p);
    sim.launch(vx, vy);
    const t0 = sim.t;
    while (sim.t - t0 < 7) { sim.step(); steps++; if (sim.status !== 'play') break; if (sim.t - t0 > 0.15 && sim.canLaunch()) break; }
  });
  for (let i = 0; i < 60 * 8 && sim.status === 'play'; i++) sim.step(); // the game keeps running after the last flip
  return { at, status: sim.status, reachedAt: steps };
}

let changed = 0, broken = [];
LEVELS.forEach((L, li) => {
  const wi = Math.floor(li / 20);
  const oldWaits = L.solution.map(s => Math.round((s[2] || 0) / PHYS.DT));
  const ref = replay(Old.Sim, L, wi, oldWaits);
  if (ref.status !== 'win') { broken.push(`${li + 1}: does not win with the previous physics either`); return; }
  // walk the route with the current physics, flipping at the reference steps
  const { sim, steps: s0 } = start(Sim, L, wi);
  let steps = s0;
  const waits = [];
  for (const [k, [a, p]] of L.solution.entries()) {
    const target = ref.at[k].step;
    const w = target - steps;
    if (w < 0) { broken.push(`${li + 1}: flip ${k + 1} would be due before the sausage is ready`); return; }
    waits.push(w);
    for (let i = 0; i < w; i++) { sim.step(); steps++; }
    if (!sim.canLaunch() || sim.px[4] !== ref.at[k].x || sim.py[4] !== ref.at[k].y) { broken.push(`${li + 1}: flip ${k + 1} is not at the same state`); return; }
    const [vx, vy] = Sim.clampLaunch(Math.cos(a), Math.sin(a), p);
    sim.launch(vx, vy);
    const t0 = sim.t;
    while (sim.t - t0 < 7) { sim.step(); steps++; if (sim.status !== 'play') break; if (sim.t - t0 > 0.15 && sim.canLaunch()) break; }
  }
  const check = replay(Sim, L, wi, waits);
  if (check.status !== 'win') { broken.push(`${li + 1}: the re-timed route does not win (${check.status})`); return; }
  if (waits.some((w, k) => w !== oldWaits[k])) {
    changed++;
    console.log(`${li + 1} ${L.name}: waits ${oldWaits.map(w => (w * PHYS.DT).toFixed(2)).join(' ')} → ${waits.map(w => (w * PHYS.DT).toFixed(2)).join(' ')}`);
    L.solution.forEach((s, k) => { s[2] = +(waits[k] * PHYS.DT).toFixed(6); });
  }
});

console.log(`${changed} route(s) re-timed, ${broken.length} problem(s)`);
for (const b of broken) console.log('  ✗ ' + b);
if (args.includes('--write') && !broken.length) {
  const file = path.resolve(path.dirname(new URL(import.meta.url).pathname), '../src/levels/data.js');
  fs.writeFileSync(file, '// AUTO-GENERATED by tools/generate.mjs (+ tools/tune-par.mjs) — every level verified solvable by tools/solver.mjs\nexport const LEVELS = ' + JSON.stringify(LEVELS) + ';\n');
  console.log('written', path.relative(process.cwd(), file));
}
process.exit(broken.length ? 1 : 0);
