// Par tuning: par starts at the solver's fewest-flip route, then gets slack where that route is
// rarely executed cleanly by a human (measured by replaying it with human-sized error).
// Rewrites src/levels/data.js in place, keeping the solver minimum as `minFlips`.
import fs from 'node:fs';
import path from 'node:path';
import { perturbedRate } from './qa.mjs';

const file = path.resolve('src/levels/data.js');
const { LEVELS } = await import(file + '?t=' + Date.now());
const N = 24;
const report = [];
LEVELS.forEach((L, i) => {
  if (!L) throw new Error('missing level ' + i);
  const min = L.minFlips ?? L.par;
  const rate = perturbedRate({ ...L, par: min }, Math.floor(i / 20), N, 1000 + i);
  let slack = 0;
  if (rate < 0.25) slack++;
  if (rate < 0.06 && min >= 4) slack++;
  L.minFlips = min;
  L.par = min + slack;
  report.push(`#${i + 1} min ${min} → par ${L.par}  (clean-route ${(rate * 100).toFixed(0)}%)`);
});
fs.writeFileSync(file, '// AUTO-GENERATED by tools/generate.mjs (+ tools/tune-par.mjs) — every level verified solvable by tools/solver.mjs\nexport const LEVELS = ' + JSON.stringify(LEVELS) + ';\n');
console.log(report.join('\n'));
const slackCount = LEVELS.filter(l => l.par > l.minFlips).length;
console.log(`tuned ${LEVELS.length} levels; ${slackCount} got extra par`);
