backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: "Search description", name: description, widget: text}
          - {label: Image, name: image, widget: image}
          - {label: "Intro", name: intro, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Steps", name: steps, widget: list, fields: [
              {label: "Image", name: "image", widget: "image"},
              {label: "Title", name: "title", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Sample entry", name: sample, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"},
              {label: "Date", name: "date", widget: string},
              {label: "Quote", name: "quote", widget: "text"},
              {label: "Tags", name: "tags", widget: list, fields: [
                {label: "Label", name: "label", widget: string},
                {label: "Value", name: "value", widget: string}]}]}
          - {label: "Plus", name: plus, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"},
              {label: "Image", name: "image", widget: "image"},
              {label: "Image description", name: "imageAlt", widget: string}]}
      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: "Search description", name: description, widget: string}
          - {label: Body, name: body, widget: markdown}
      - file: "site/content/features/_index.md"
        label: "Features Page"
        name: "features"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: "Search description", name: description, widget: text}
          - {label: Image, name: image, widget: image}
          - {label: "Free features", name: free, widget: object, fields: [
              {label: Heading, name: heading, widget: string},
              {label: Description, name: description, widget: text},
              {label: Items, name: items, widget: list, fields: [
                {label: Image, name: image, widget: image},
                {label: Title, name: title, widget: string},
                {label: Text, name: text, widget: text}]}]}
          - {label: "Plus features", name: plus, widget: object, fields: [
              {label: Heading, name: heading, widget: string},
              {label: Description, name: description, widget: text},
              {label: Items, name: items, widget: list, fields: [
                {label: Image, name: image, widget: image},
                {label: Title, name: title, widget: string},
                {label: Text, name: text, widget: text}]}]}
          - {label: Pricing, name: pricing, widget: object, fields: [
              {label: Heading, name: heading, widget: string},
              {label: Description, name: description, widget: text},
              {label: Plans, name: plans, widget: list, fields: [
                {label: Plan, name: plan, widget: string},
                {label: Price, name: price, widget: string},
                {label: Period, name: period, widget: string, required: false},
                {label: Description, name: description, widget: string},
                {label: Items, name: items, widget: list}]}]}
