// Screenshots of a forced Legendary pull and a Rare figure reveal.  node tools/gacha-visual.mjs
import { chromium } from 'playwright';
import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../www');
const types = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.png': 'image/png', '.woff2': 'font/woff2', '.webmanifest': 'application/manifest+json' };
const server = http.createServer((req, res) => { const f = path.join(root, req.url.split('?')[0] === '/' ? 'index.html' : req.url.split('?')[0]); if (!fs.existsSync(f)) { res.writeHead(404); return res.end(); } res.writeHead(200, { 'content-type': types[path.extname(f)] || 'application/octet-stream' }); fs.createReadStream(f).pipe(res); }).listen(0);
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true });
const page = await ctx.newPage();
page.on('pageerror', (e) => console.error('PAGEERROR', e.message));
await page.goto(`http://localhost:${server.address().port}/?debug`);
await page.waitForSelector('#boot.gone', { state: 'attached' });
await page.evaluate(() => { const { G } = window.__tt; G.tutorialSkip(); G.state.cur.coins = 50; G.ui.closeAllModals(); G.state.gacha.pityL = 59; });
await page.waitForTimeout(400);
await page.click('#fab-capsule button');
await page.waitForSelector('#gz-cv');
await page.click('[data-gz="pull:1:coin"]', { force: true });
await page.waitForSelector('[data-gz="open:0"]', { timeout: 9000 });
await page.waitForTimeout(500);
await page.screenshot({ path: '/tmp/tt/gzv-1-legend-capsule.png' });
await page.click('[data-gz="open:0"]', { force: true });
await page.waitForTimeout(650);
await page.screenshot({ path: '/tmp/tt/gzv-2-opening.png' });
await page.waitForSelector('#gz-cap:not([hidden])');
await page.waitForTimeout(900);
await page.screenshot({ path: '/tmp/tt/gzv-3-legend-reveal.png' });
console.log(await page.evaluate(() => document.querySelector('#gz-cap').innerText.replace(/\n/g, ' | ')));
await browser.close(); server.close();
