/*
 * Rainkeep painted art: hero and cast portraits, one painting per foe family, a backdrop per act, the
 * title painting, building headers, event banners, store art, the twelve Dunes ruins and the three
 * endings, all made with Higgsfield (GPT Image 2) and stored as WebP under art/. art2d.js turns this map
 * into one stylesheet; anything missing here keeps its drawn SVG art. The single-file build swaps each
 * path for an inline data URI.
 */
'use strict';
window.RK_ART = {
  portrait: {
    zahra: 'art/portraits/zahra.webp',
    tariq: 'art/portraits/tariq.webp',
    leila: 'art/portraits/leila.webp',
    idris: 'art/portraits/idris.webp',
    soraya: 'art/portraits/soraya.webp',
    nadia: 'art/portraits/nadia.webp',
    bashir: 'art/portraits/bashir.webp',
    amira: 'art/portraits/amira.webp',
    kofi: 'art/portraits/kofi.webp',
    yara: 'art/portraits/yara.webp',
    rashid: 'art/portraits/rashid.webp',
    samira: 'art/portraits/samira.webp',
    omar: 'art/portraits/omar.webp',
    nuri: 'art/portraits/nuri.webp',
    halima: 'art/portraits/halima.webp',
    lio: 'art/portraits/lio.webp',
    tamir: 'art/portraits/tamir.webp',
    mara: 'art/portraits/mara.webp',
    imani: 'art/portraits/imani.webp',
    kaveh: 'art/portraits/kaveh.webp',
    tomas: 'art/portraits/tomas.webp',
    sefa: 'art/portraits/sefa.webp',
    maram: 'art/portraits/maram.webp',
    hadi: 'art/portraits/hadi.webp',
    nima: 'art/portraits/nima.webp',
  },
  foe: {
    raider: 'art/foes/raider.webp',
    beast: 'art/foes/beast.webp',
    scorpion: 'art/foes/scorpion.webp',
    serpent: 'art/foes/serpent.webp',
    drake: 'art/foes/drake.webp',
    spirit: 'art/foes/spirit.webp',
    construct: 'art/foes/construct.webp',
    crystal: 'art/foes/crystal.webp',
    sun: 'art/foes/sun.webp',
    void: 'art/foes/void.webp',
  },
  scene: {
    act1: 'art/scenes/act1.webp',
    act2: 'art/scenes/act2.webp',
    act3: 'art/scenes/act3.webp',
  },
  building: {
    shelter: 'art/buildings/shelter.webp',
    quarry: 'art/buildings/quarry.webp',
    grove: 'art/buildings/grove.webp',
    well: 'art/buildings/well.webp',
    mine: 'art/buildings/mine.webp',
    infirmary: 'art/buildings/infirmary.webp',
    barracks: 'art/buildings/barracks.webp',
    watchtower: 'art/buildings/watchtower.webp',
    archive: 'art/buildings/archive.webp',
    hall: 'art/buildings/hall.webp',
    storehouse: 'art/buildings/storehouse.webp',
    forge: 'art/buildings/forge.webp',
  },
  event: {
    rainfest: 'art/events/rainfest.webp',
    hunt: 'art/events/hunt.webp',
    builder: 'art/events/builder.webp',
    forgefest: 'art/events/forgefest.webp',
    spirerush: 'art/events/spirerush.webp',
    oasis: 'art/events/oasis.webp',
  },
  offer: {
    founder: 'art/offers/founder.webp',
    stipend: 'art/offers/stipend.webp',
    ledger: 'art/offers/ledger.webp',
    growth: 'art/offers/growth.webp',
    stormkit: 'art/offers/stormkit.webp',
    warchest: 'art/offers/warchest.webp',
    forgekit: 'art/offers/forgekit.webp',
    lvpack: 'art/offers/lvpack.webp',
    lvpack2: 'art/offers/lvpack2.webp',
    sg1: 'art/offers/sg1.webp',
    sg2: 'art/offers/sg2.webp',
    sg3: 'art/offers/sg3.webp',
    sg4: 'art/offers/sg4.webp',
    sg5: 'art/offers/sg5.webp',
    sg6: 'art/offers/sg6.webp',
  },
  ruin: {
    cart: 'art/ruins/cart.webp',
    wagons: 'art/ruins/wagons.webp',
    observatory: 'art/ruins/observatory.webp',
    bunker: 'art/ruins/bunker.webp',
    chapel: 'art/ruins/chapel.webp',
    airship: 'art/ruins/airship.webp',
    den: 'art/ruins/den.webp',
    pool: 'art/ruins/pool.webp',
    forge: 'art/ruins/forge.webp',
    shrine: 'art/ruins/shrine.webp',
    scouts: 'art/ruins/scouts.webp',
    mine: 'art/ruins/mine.webp',
  },
  ending: {
    act1: 'art/endings/act1.webp',
    act2: 'art/endings/act2.webp',
    act3: 'art/endings/act3.webp',
  },
  title: 'art/title.webp',
};
